### ISSUE TITLE
create-react-microservice failing on windows

### ISSUE THREAD

**Issue by tsukhu** [ImmoweltGroup/create-react-microservice#217]
### Describe the problem:
create-react-microservice failing on windows
#### Steps to reproduce:

Run create-react-microservice to create a mono-repo on a Windows machine

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
```bash
create-react-microservice test-ui-microservice
? What is the preffered license for the mono repository and its packages? (Use a
rrow keys)
> Unlicense
? What is the preffered license for the mono repository and its packages? MIT
? What is the NPM organization scope for the mono repositories packages? @TFG
? What is the NPM organization scope for the mono repositories packages? @tfg/
? What is the git repository URL for the mono repositories packages? https://github.com/ERS-HCL/react-microservice.git
? What is the git repository URL for the mono repositories packages? https://git
hub.com/ERS-HCL/react-microservice.git
{ Error: E:\workspace\test-ui-microservice\E:\Users\tsukhu\AppData\Local\Yarn\Data\global\node_modules\create-react-microservice-scaffold\src\__tests__ contains invalid WIN32 path characters.
    at Object.mkdirs (E:\Users\tsukhu\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at Object.mkdirs (E:\Users\tsukhu\AppData\Local\Yarn\Data\global\node_modules\universalify\index.js:5:67)
    at pathExists (E:\Users\tsukhu\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\output\index.js:20:11)
    at fn.apply.then.r (E:\Users\tsukhu\AppData\Local\Yarn\Data\global\node_modules\universalify\index.js:23:46)
    at <anonymous> code: 'EINVAL' }
```

**Comment by kevroadrunner** [comment]
Thank you @tsukhu! @Inkdpixels: May we integrate [AppVeyor](https://www.appveyor.com/) to prevent windows issues like these?!

**Comment by Romischart** [comment]
It would be interesting for us to know which os you were currently using.
For example win 10 x64?

**Comment by tsukhu** [comment]
Windows 8.1 x64

**Comment by TheAifam5** [comment]
Its just a problem with ‘E:\workspace\test-ui-microservice\E:\Users\tsukhu\AppData\Local\Yarn\Data\global\node_modules\create-react-microservice-scaffold\src\__tests__’

Just simply read an error and this issue could be patched in max 30 minutes. 
I’m gonna make a pull request for that.

**Comment by TheAifam5** [comment]
That problem should be gone for now. :)

**Comment by Inkdpixels** [comment]
@TheAifam5 Not yet unfortunately, the fix is merged but the release was not automatically triggered. Will fix it this evening hopefully and close this issue once the dependency tree has been updated.

**Comment by tsukhu** [comment]
Great !! waiting for this one ...
